# Site settings
title: Road to IPM
email: roadtoipm@gmail.com
description: Welcome to Road to IPM - Your One Stop Solution for getting into IPM IIM
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/roadtoipm/
linkedin_url: https://in.linkedin.com/company/roadtoipm
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
